export const ARTICLES_IS_RECEIVED = 'ARTICLES_IS_RECEIVED';
export const ARTICLE_PAGE_IS_RECEIVED = 'ARTICLE_PAGE_IS_RECEIVED';
export const PAGE_IS_CHANGED = 'PAGE_IS_CHANGED';
export const ARTICLES_LOADING_ERROR = 'ARTICLES_LOADING_ERROR';
export const ARTICLES_LOADING_START = 'ARTICLES_LOADING_START';
export const ARTICLES_LOADING_END = 'ARTICLES_LOADING_END';
export const ARTICLE_PAGE_LOADING_ERROR = 'ARTICLE_PAGE_LOADING_ERROR';
export const ARTICLE_PAGE_LOADING_START = 'ARTICLE_PAGE_LOADING_START';
export const ARTICLE_PAGE_LOADING_END = 'ARTICLE_PAGE_LOADING_END';
export const USERS_REGISTRATION_LOADING_ERROR = 'USERS_REGISTRATION_LOADING_ERROR';
export const USERS_REGISTRATION_LOADING_START = 'USERS_REGISTRATION_LOADING_START';
export const USERS_REGISTRATION_LOADING_END = 'USERS_REGISTRATION_LOADING_END';
export const USERS_REGISTRATION_ERRORS = 'USERS_REGISTRATION_ERRORS';
export const USERS_REGISTRATION_SUCCESS = 'USERS_REGISTRATION_SUCCESS';
export const USERS_AUTHENTICATION_LOADING_ERROR = 'USERS_AUTHENTICATION_LOADING_ERROR';
export const USERS_AUTHENTICATION_LOADING_START = 'USERS_AUTHENTICATION_LOADING_START';
export const USERS_AUTHENTICATION_LOADING_END = 'USERS_AUTHENTICATION_LOADING_END';
export const USERS_AUTHENTICATION_ERRORS = 'USERS_AUTHENTICATION_ERRORS';
export const USERS_AUTHENTICATION_SUCCESS = 'USERS_AUTHENTICATION_SUCCESS';
export const USER_IS_LOGGED = 'USER_IS_LOGGED';
export const LOGOUT = 'LOGOUT';
export const USERS_EDITING_LOADING_ERROR = 'USERS_EDITING_LOADING_ERROR';
export const USERS_EDITING_LOADING_START = 'USERS_EDITING_LOADING_START';
export const USERS_EDITING_LOADING_END = 'USERS_EDITING_LOADING_END';
export const USERS_EDITING_ERRORS = 'USERS_EDITING_ERRORS';
export const USERS_EDITING_SUCCESS = 'USERS_EDITING_SUCCESS';
export const CHANGED_TAGS_INFO_ON_CREATE_ARTICLE_PAGE = 'CHANGED_TAGS_INFO_ON_CREATE_ARTICLE_PAGE';
export const CHANGED_MAX_TAG_INDEX_ON_CREATE_ARTICLE_PAGE =
  'CHANGED_MAX_TAG_INDEX_ON_CREATE_ARTICLE_PAGE';

const ActionTypes = {
  ARTICLES_IS_RECEIVED,
  ARTICLE_PAGE_IS_RECEIVED,
  PAGE_IS_CHANGED,
  ARTICLES_LOADING_ERROR,
  ARTICLES_LOADING_START,
  ARTICLES_LOADING_END,
  ARTICLE_PAGE_LOADING_ERROR,
  ARTICLE_PAGE_LOADING_START,
  ARTICLE_PAGE_LOADING_END,
  USERS_REGISTRATION_LOADING_ERROR,
  USERS_REGISTRATION_LOADING_START,
  USERS_REGISTRATION_LOADING_END,
  USERS_REGISTRATION_ERRORS,
  USERS_REGISTRATION_SUCCESS,
  USERS_AUTHENTICATION_LOADING_ERROR,
  USERS_AUTHENTICATION_LOADING_START,
  USERS_AUTHENTICATION_LOADING_END,
  USERS_AUTHENTICATION_ERRORS,
  USERS_AUTHENTICATION_SUCCESS,
  USER_IS_LOGGED,
  LOGOUT,
  USERS_EDITING_LOADING_ERROR,
  USERS_EDITING_LOADING_START,
  USERS_EDITING_LOADING_END,
  USERS_EDITING_ERRORS,
  USERS_EDITING_SUCCESS,
  CHANGED_TAGS_INFO_ON_CREATE_ARTICLE_PAGE,
  CHANGED_MAX_TAG_INDEX_ON_CREATE_ARTICLE_PAGE,
};

export default ActionTypes;
