export const ARTICLES_IS_RECEIVED = 'ARTICLES_IS_RECEIVED';
export const ARTICLE_PAGE_IS_RECEIVED = 'ARTICLE_PAGE_IS_RECEIVED';
export const PAGE_IS_CHANGED = 'PAGE_IS_CHANGED';
export const ARTICLES_LOADING_ERROR = 'ARTICLES_LOADING_ERROR';
export const ARTICLES_LOADING_START = 'ARTICLES_LOADING_START';
export const ARTICLES_LOADING_END = 'ARTICLES_LOADING_END';
export const ARTICLE_PAGE_LOADING_ERROR = 'ARTICLE_PAGE_LOADING_ERROR';
export const ARTICLE_PAGE_LOADING_START = 'ARTICLE_PAGE_LOADING_START';
export const ARTICLE_PAGE_LOADING_END = 'ARTICLE_PAGE_LOADING_END';

const ActionTypes = {
  ARTICLES_IS_RECEIVED,
  ARTICLE_PAGE_IS_RECEIVED,
  PAGE_IS_CHANGED,
  ARTICLES_LOADING_ERROR,
  ARTICLES_LOADING_START,
  ARTICLES_LOADING_END,
  ARTICLE_PAGE_LOADING_ERROR,
  ARTICLE_PAGE_LOADING_START,
  ARTICLE_PAGE_LOADING_END,
};

export default ActionTypes;
